package com.tj720.model.common;

import java.util.Date;

public class MipAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_id
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_name
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_size
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private Long attSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_path
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_isJunk
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attIsjunk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_date
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private Date attDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_type
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.attr_user
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attrUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_fk_id
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attFkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_file_type
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private Integer attFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_attachment.att_source
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    private String attSource;

    private String isMain;

    public String getIsMain() {
        return isMain;
    }

    public void setIsMain(String isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_id
     *
     * @return the value of mip_attachment.att_id
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttId() {
        return attId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_id
     *
     * @param attId the value for mip_attachment.att_id
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttId(String attId) {
        this.attId = attId == null ? null : attId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_name
     *
     * @return the value of mip_attachment.att_name
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttName() {
        return attName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_name
     *
     * @param attName the value for mip_attachment.att_name
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttName(String attName) {
        this.attName = attName == null ? null : attName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_size
     *
     * @return the value of mip_attachment.att_size
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public Long getAttSize() {
        return attSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_size
     *
     * @param attSize the value for mip_attachment.att_size
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttSize(Long attSize) {
        this.attSize = attSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_path
     *
     * @return the value of mip_attachment.att_path
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttPath() {
        return attPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_path
     *
     * @param attPath the value for mip_attachment.att_path
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttPath(String attPath) {
        this.attPath = attPath == null ? null : attPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_isJunk
     *
     * @return the value of mip_attachment.att_isJunk
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttIsjunk() {
        return attIsjunk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_isJunk
     *
     * @param attIsjunk the value for mip_attachment.att_isJunk
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttIsjunk(String attIsjunk) {
        this.attIsjunk = attIsjunk == null ? null : attIsjunk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_date
     *
     * @return the value of mip_attachment.att_date
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public Date getAttDate() {
        return attDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_date
     *
     * @param attDate the value for mip_attachment.att_date
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttDate(Date attDate) {
        this.attDate = attDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_type
     *
     * @return the value of mip_attachment.att_type
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttType() {
        return attType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_type
     *
     * @param attType the value for mip_attachment.att_type
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttType(String attType) {
        this.attType = attType == null ? null : attType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.attr_user
     *
     * @return the value of mip_attachment.attr_user
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttrUser() {
        return attrUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.attr_user
     *
     * @param attrUser the value for mip_attachment.attr_user
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttrUser(String attrUser) {
        this.attrUser = attrUser == null ? null : attrUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_fk_id
     *
     * @return the value of mip_attachment.att_fk_id
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttFkId() {
        return attFkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_fk_id
     *
     * @param attFkId the value for mip_attachment.att_fk_id
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttFkId(String attFkId) {
        this.attFkId = attFkId == null ? null : attFkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_file_type
     *
     * @return the value of mip_attachment.att_file_type
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public Integer getAttFileType() {
        return attFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_file_type
     *
     * @param attFileType the value for mip_attachment.att_file_type
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttFileType(Integer attFileType) {
        this.attFileType = attFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_attachment.att_source
     *
     * @return the value of mip_attachment.att_source
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public String getAttSource() {
        return attSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_attachment.att_source
     *
     * @param attSource the value for mip_attachment.att_source
     *
     * @mbggenerated Mon Jul 02 10:27:45 CST 2018
     */
    public void setAttSource(String attSource) {
        this.attSource = attSource == null ? null : attSource.trim();
    }
}