package com.tj720.model.common;

import java.util.Date;

public class SysDict {
    private String pid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.id
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_type
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String dictType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_code
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_name
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String dictName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_order
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String dictOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.description
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.create_by
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.create_date
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_type
     *
     * @return the value of sys_dict.dict_type
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_type
     *
     * @param dictType the value for sys_dict.dict_type
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_code
     *
     * @return the value of sys_dict.dict_code
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_code
     *
     * @param dictCode the value for sys_dict.dict_code
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_name
     *
     * @return the value of sys_dict.dict_name
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_name
     *
     * @param dictName the value for sys_dict.dict_name
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_order
     *
     * @return the value of sys_dict.dict_order
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getDictOrder() {
        return dictOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_order
     *
     * @param dictOrder the value for sys_dict.dict_order
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setDictOrder(String dictOrder) {
        this.dictOrder = dictOrder == null ? null : dictOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.description
     *
     * @return the value of sys_dict.description
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.description
     *
     * @param description the value for sys_dict.description
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_by
     *
     * @return the value of sys_dict.create_by
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_by
     *
     * @param createBy the value for sys_dict.create_by
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_date
     *
     * @return the value of sys_dict.create_date
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_date
     *
     * @param createDate the value for sys_dict.create_date
     *
     * @mbggenerated Thu Sep 20 15:43:56 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }
}